% ArrayFactorCode32x32.m
% Data-driven AF post-processing for the 32x32 BM-BFN Simulink model
% Uses the model-generated phase data directly

clearvars -except PhaseValuesDegToWorkspace32x32
close all; clc;

% -------------------------------------------------
% Basic settings
% -------------------------------------------------
N = 32;                      % Number of array elements / outputs
numBeamsExpected = 32;       % Expected number of beam states
d = 0.5;                     % Element spacing in wavelengths
theta = -90:0.1:90;          % Angle sweep in degrees

% -------------------------------------------------
% Load phase data from workspace first, else from file
% -------------------------------------------------
if exist('PhaseValuesDegToWorkspace32x32','var')
    phaseStore = PhaseValuesDegToWorkspace32x32;
else
    candidateFiles = { ...
        'PhaseValuesDegToFile32x32.mat', ...
        'PhaseValuesDegToFile32x32' ...
    };

    foundFile = '';
    for k = 1:numel(candidateFiles)
        if exist(candidateFiles{k}, 'file')
            foundFile = candidateFiles{k};
            break;
        end
    end

    if isempty(foundFile)
        error(['No phase data found. Run the Simulink model first so that ', ...
               'PhaseValuesDegToWorkspace32x32 (or the saved file) is created.']);
    end

    S = load(foundFile);

    % Prefer the known variable name if present
    if isfield(S, 'PhaseValuesDegToFileVariable')
        phaseStore = S.PhaseValuesDegToFileVariable;
    else
        fn = fieldnames(S);
        phaseStore = S.(fn{1});
    end
end

% -------------------------------------------------
% Convert timeseries / structures to numeric matrix if needed
% -------------------------------------------------
if isa(phaseStore, 'timeseries')
    phaseStore = phaseStore.Data;
elseif isstruct(phaseStore)
    if isfield(phaseStore, 'signals') && isfield(phaseStore.signals, 'values')
        phaseStore = phaseStore.signals.values;
    elseif isfield(phaseStore, 'Data')
        phaseStore = phaseStore.Data;
    else
        error('Unsupported structured phase-data format.');
    end
end

phaseStore = squeeze(phaseStore);

% Ensure 2D numeric matrix
if ~isnumeric(phaseStore)
    error('Phase data is not numeric after loading/conversion.');
end

if ~ismatrix(phaseStore)
    error('Phase data must reduce to a 2D matrix: [samples x channels].');
end

% Only need the first 32 columns (32 output phases)
if size(phaseStore,2) < N
    error('Phase data has fewer than 32 columns. Check model logging configuration.');
end

phaseStore = phaseStore(:, 1:N);

% -------------------------------------------------
% Detect distinct beam states directly from the logged data
% -------------------------------------------------
% Small rounding removes insignificant numerical jitter
phaseRounded = round(phaseStore, 6);

% Mark rows where the phase state changes
changeMask = [true; any(diff(phaseRounded, 1, 1) ~= 0, 2)];

% Keep one representative row per distinct state
phaseUniqueDeg = phaseStore(changeMask, :);

% Remove repeated states that may recur later
% 'stable' preserves order as generated by the model
[phaseUniqueRoundedStable, ia] = unique(round(phaseUniqueDeg, 6), 'rows', 'stable');
phaseUniqueDeg = phaseUniqueDeg(sort(ia), :);

% If more than 32 states are present, keep the first 32
if size(phaseUniqueDeg, 1) < numBeamsExpected
    error(['Only ', num2str(size(phaseUniqueDeg,1)), ...
           ' distinct beam states were detected; expected 32.']);
elseif size(phaseUniqueDeg, 1) > numBeamsExpected
    warning(['More than 32 distinct states detected (', ...
             num2str(size(phaseUniqueDeg,1)), '). Keeping the first 32.']);
    phaseUniqueDeg = phaseUniqueDeg(1:numBeamsExpected, :);
end

% Final beam-state matrix: 32 beams x 32 element phases
phaseMatrixDeg = phaseUniqueDeg;
phaseMatrixRad = deg2rad(phaseMatrixDeg);

% -------------------------------------------------
% Compute array factor using the full 32-element phase vector
% -------------------------------------------------
AFall = zeros(numBeamsExpected, numel(theta));

n = (0:N-1).';                % Element indices as column vector
psi = 2*pi*d*sind(theta);     % Spatial phase term

for b = 1:numBeamsExpected
    phi = phaseMatrixRad(b, :).';   % 32x1 phase vector for beam b

    % Full phasor summation across all elements
    AF = abs(sum(exp(1j*(n*psi + phi)), 1)) / N;

    AFall(b, :) = AF;
end

% -------------------------------------------------
% Global normalization across all beams
% -------------------------------------------------
maxAF = max(AFall(:));
if maxAF <= 0
    error('Computed AF is zero everywhere. Check phase data.');
end
AFall = AFall / maxAF;

% -------------------------------------------------
% Plot all 32 beams in one Cartesian figure
% -------------------------------------------------
figure('Name', '32x32 Butler Matrix - Normalized Cartesian AF');
plot(theta, AFall.', 'LineWidth', 1);
grid on;
xlim([-90 90]);
ylim([0 1.05]);
xlabel('Angle [Degrees]');
ylabel('Normalized Array Factor');
title('32x32 Butler Matrix: 32 Normalized Beams (Cartesian)');
set(gca, 'FontSize', 11);

% -------------------------------------------------
% Print detected main-beam directions
% -------------------------------------------------
[~, idxMax] = max(AFall, [], 2);
beamAnglesDeg = theta(idxMax);

disp('Detected beam-state phase matrix size (beams x outputs):');
disp(size(phaseMatrixDeg));

disp('Estimated main beam directions from AF peaks (degrees):');
disp(beamAnglesDeg.');

% Optional: export results to workspace for further checks
assignin('base', 'PhaseMatrixDeg_32x32', phaseMatrixDeg);
assignin('base', 'AFall_32x32', AFall);
assignin('base', 'BeamAnglesDeg_32x32', beamAnglesDeg);
assignin('base', 'ThetaDeg_32x32', theta);